name: Build frontend and publish static
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: corepack enable && corepack prepare pnpm@9 --activate
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - run: pnpm run build
        working-directory: frontend
      - run: |
          rm -rf src/static && mkdir -p src/static
          cp -r frontend/dist/* src/static/
      - name: Commit built static
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A src/static
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update static build [skip ci]"
            git push
          fi
